### ISSUE TITLE
CERTS_ADMIN

### ISSUE THREAD

**Issue by ssadok** [blockchain-monitoring/blockchain-monitoring#20]
in docker-compose 
https://github.com/blockchain-monitoring/blockchain-monitoring/blob/master/docker/docker-compose.yml#L12

i didn't understant what is $CERTS_ADMIN

can you help me please ?

**Comment by andreevym** [comment]
Hello!
this is the folder where to store certificates from "net-config.yaml"

for example

**net-config.yaml**
```
organisations:
- name: 'foo'
  msp: 'foo'
  member:
    login: 'foomember'
    password: 'member'
  ca:
    name: 'cafoo'
    address: 'http://172.25.0.177:7054'
  peers:
    - name: 'peer-foo'
      address: 'grpc://172.25.0.104:7051'
      admin:
        login: 'fooadmin'
        **privkey: /opt/blockchain-monitoring/certs/admin/**foo/foo-admin-key.pem
        **cert:    /opt/blockchain-monitoring/certs/admin/**foo/foo-admin-signed.pem
```

and docker-compose mapping
$CERTS_ADMIN on the folder $CERTS_ADMIN
